### ISSUE TITLE
Server does not sanitize upload requests

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#40]
eDiscovery Recipient is displaying upload and upload folder icons. the process get's 200 responses but doesn't seem to upload a file. I'm unclear if this is an AllowedOperations list problem from the server or if the client is always assuming upload rights?

**Comment by coler706** [comment]
The buttons will be hidden when we make use of the fetch manager object that has the op list.
The server should be doing validation of folder names that the client creates/uploads. It is currently returning a 200 because it seems to be doing no validation. Fixing this would also fix some bugs involving unsanitized path creations corrupting cases.
