### ISSUE TITLE
Review ffmpeg codec formats and options

### ISSUE THREAD

**Issue by andylippitt** [NYPTI/DEMS#5]
The current system is setup to create a CBR h.264 .mp4 file and a webm.

The .mp4 seems low quality and should probably be VBR. We're interested more in format conversion that recompression. Scaling and detail of original should be preserved as near best effort.

Webm seems it may not be required at all anymore for mobile device support. The output also seems too large when comparerd with the .mp4

**Comment by andylippitt** [comment]
also briefly review whether we might gain significant advantage using a GPU instance in EC2

**Comment by seansmith** [comment]
Please evaluate - possibility of dropping Webm - with two MP4 formats (PC/Mobile) - looks like since we started this project there is far more traction on MP4 working in most browsers.  
Source: https://www.ionos.com/digitalguide/websites/website-creation/webm/ and 
https://caniuse.com/#feat=webm
https://caniuse.com/#feat=mpeg4
.mp4 files are currently better supported by browsers and have also had better support historically (which matters in environments where Operating Systems aren't up to date).

May be better to have a mobile/low bit rate transcoded video alongside a higher bit rate transcode:

mobile.mp4 primarily for audio consumption
Resolution: <=360p
Video Bitrate: 400kbps
Audio Bitrate: 96kbps
Sample command: ffmpeg -i original.mp4 -vf scale=640:360 -threads 3 -movflags +faststart -c:v libx264 -preset veryfast -b:v 400k -c:a aac -b:a 96k output.mp4
File size estimate: 218 MB/hr


PC.mp4 for HD (720) viewing on PC
Resolution: <=720p
Video Bitrate: 3000kbps
Audio Bitrate: 128kbps
Sample command: ffmpeg -i original.mp4 -vf scale=1280:720 -threads 3 -movflags +faststart -c:v libx264 -preset veryfast -b:v 2200k -c:a aac -b:a 128k output.mp4
File size estimate: 1.0 GB/hr


Total transcoded video playback time per 1 TB: <850 hours
^this figure above only accounts for the transcoded copies and does not account for the original uploaded file.
Therefore, for each uploaded video file, there will be 3 total files stored on Documents:
Original.*
PC_version.mp4
Mobile_version.mp4

Looking for guidance on this one before making decision.

**Comment by seansmith** [comment]
To wrap:  
1. Would like to capitalize on GPU
We should end up with 3 versions of Video:
1.  Original Uploaded
2.  720p encoded veryfast at Bitrate 2200 - filesize should be a little less than original (that's what we found in test)
3,  360p encoded veryfast at bitrate 400

For download - only two options:
1. Original and MP4 (720p version).

**Comment by julien-cheng** [comment]
Implementation notes on GPU:
- ffmpeg needs to be compiled with hardware acceleration support
- input file decoding can be hardware accelerated by CUDA for the following formats. Software decoding would be necessary if the input file is not in a format below; set ffmpeg to run multithreaded.
    - h263
    - h264
    - hevc
    - mjpeg
    - mpeg1
    - mpeg2
    - mpeg4
    - vc1
    - vp8
    - vp9
- output file encoding can be hardware accelerated by NVENC:
    - h264
    - h265 (not recommended. browser adoption is abysmal at ~17%)
- for the output encoding preset, do not set it too fast. the GPU acceleration makes the encoding process between 8-80x faster than the video length. save disk space by using a slower preset and lower bitrate
    - `fast` (not recommended)
    - `medium` (minimum recommended)
    - `slow` (most preferable)
    - example PC setting: slow 2000k, medium 2200k
    - example mobile setting: slow 350k, medium 400k
- the presets that are available don't include granular settings like `veryfast` or `slower`. list of nvenc h.264 presets are `default`, `slow`, `medium`, `fast`, `hp`, `hq`, `bd`, `ll`, `llhq`, `llhp`, `lossless`, `losslesshp` where
    - `hp` means high performance
    - `hq` means high quality
    - `ll` means low latency
    - `bd` means bluray disk
